### ISSUE TITLE
Can not search by pool id

### ISSUE THREAD

**Issue by Sasquire** [e621ng/e621ng#147]
Searching by pool ids return no posts.

This issue also seems to affect searching by pool name for pools with spaces in the name.

**Comment by kiranoot** [comment]
This appears to be a search index update problem with pools. It may be time to remove the pool_string on the posts table, or maybe it's not. I'll investigate a solution for this tomorrow.

Note to self: Searching by pool names is almost meaningless at this time because pools allow spaces in their names, but the search syntax does not.

**Comment by kiranoot** [comment]
Fixed the search by id issues in 46bacc13d8272fa0e5bc6eedbafe54

The by name option seems to be mostly broken, and the search parser isn't set up to deal with spaces, so I'm deferring that for later.
