### ISSUE TITLE
Pages for user listing extends too far

### ISSUE THREAD

**Issue by Sasquire** [e621ng/e621ng#190]
On the bottom of the `/users?page=1` path, the counter that counts how many pages of users extends further than it should. In fact it extends to the maximum limit set.

This is not a gigantic issue, but can be misleading and cause difficulty in viewing the actual length of the user list.

**Comment by Earlopain** [comment]
Not sure what the issue here was exactly, maybe it fixed itself. Visiting https://e621.net/users?page=1 does indeed extend the paginator all the way to 750, but since there are still results remaining this is correct.

There is an optimization for a few models where the maximum number of pages will be displayed unconditionally when not doing a search in order to avoid counting the table when it wouldn't matter anyways. I think I see the issue you're describing on my dev machine, since I have no way near the number of users for this optimization to make sense. On the other hand the number of users at the time of this issue should have been greater than 240_000 already, so maybe I'm missunderstanding something.

I closed this for now, but feel free to reopen and clarify if this is still an issue.
