### ISSUE TITLE
posts.json sometimes returns implausible data

### ISSUE THREAD

**Issue by Niko-O** [e621ng/e621ng#211]
Aside from the long-known negative post counts for some tags:
https://e621.net/tags.json?commit=Search&search[hide_empty]=no&search[name_matches]=lady&search[order]=count

I noticed that the JSON for post 6268 has some weirdness to it:
https://e621.net/posts/6268.json

score.up = 0
score.down = -2
score.total = -1559
0 - 2 does not quite add up to -1559.
From IDs 0 to 99, 69 posts have mismatches, 7 are OK (18, 21, 34, 37, 64, 66, 90) and the rest are hard-deleted.
I'd assume, up- and down-votes were not tracked back then, but this also happens with new posts: From IDs 2000000 to 2000099, only one post is OK (2000065). score.up and score.down are always very low values.
And post 2000313 has a score.up of -1. That also does not seem right.

relationships.has_children = false
relationships.has_active_children = true
If has_children is false, it should not be possible for has_active_children to be true. From IDs 0 to 99, posts 29, 30, 31, 34, 41, 45, 62, 66, 94 and 96 have this problem. I haven't checked relationships.children for those, though.)

relationships.children = []
A search for `parent:6268 status:any` on the website finds 1 active and 8 deleted posts and on it says "This post has 9 children" on the post page.

I am making authenticated requests.

**Comment by kiranoot** [comment]
Votes were not strictly ordered on the old site, and it was possible for them to become out of sync with the up and down counts without much effort. Even on the new site it may be possible, but hopefully has been solved with very strict database transaction isolation modes. Oldest posts don't have any voting backing data, so they can't be fixed. I may attempt to address newer posts, but it's possible that they as well shouldn't be corrected due to the circumstances.

The flags for children seem to be incorrect since the site import, which prevents the children field from being filled. It's on my todo list to investigate further.
