### ISSUE TITLE
Query terms that include a wildcard and resolve to no tags are ignored

### ISSUE THREAD

**Issue by Sasquire** [e621ng/e621ng#214]
**Bug overview description.**
When making a search and using the `*` wildcard, if there are no tags that match the wildcard the search will treat this term like it doesn't exist.

Search | Result
:--- | :---
`*abbbaba` | All posts
`*abbbaba -solo` | All posts without the solo tag
`sol* -solo *abbbaba` | All posts with `sol*` in the tags and not solo

**What is the expected behavior?**
Expected behavior is to return no posts. If the tag with wildcard does not relate to any tags, then it would apply to no posts.

**What actual behavior is given instead?**
Actual behavior is these terms are ignored and the search performed with the rest of the information.

**Can you reproduce the bug every time?**
Yes.

**What steps did you take to replicate this bug?**
Repeat the same search with modified queries.

**Errors or other messages returned (if any).**
Other searches that return posts when none should be returned.
* `*hampster*dance*`
* `this*should*return*nothing`
* `only*dudes male`

**Comment by liamwhite** [comment]
Instead of using Elasticsearch's wildcard feature, the approach for this in the code is based on querying the tag table to find associated tags.

https://github.com/zwagoth/e621ng/blob/b66494f84608dedd53d0313a9e66eb9da20174d7/app/models/tag.rb#L561-L578 https://github.com/zwagoth/e621ng/blob/b66494f84608dedd53d0313a9e66eb9da20174d7/app/logical/elastic_post_query_builder.rb#L54-L66

The breakdown is caused because something else is ending up in the `should` clause of this query when it is not supposed to, and ends up matching as a result.

**Comment by kiranoot** [comment]
This has been fixed in a hacky way by forcing an unknown, and invalid tag into the search, which should resolve the behavior by forcing the should to have at least one term and thus be respected instead of a no-op.

Perhaps in the future this can be fixed up in a way where the search aborts at an earlier phase so that no search has to be submitted to the backend at all.
