### ISSUE TITLE
Who favorited a post is not visible to members

### ISSUE THREAD

**Issue by Earlopain** [e621ng/e621ng#248]
Sometime during the page upgrade the list of users who faved a post was removed.
I think the reasons where that it was an expensive operation + that it was used by search engines to index.

I'd like to add that back in as a seperate page with a link to it on the posts page itself. That would prevent loading it on every post but still make it visible to those who wish to view it. That link can then also be added to `robots.txt`
Sometimes I just want to find users with similar taste.

Would you accept a merge request for this? I don't know if there were other reasons why the favorites might be hidden.

**Comment by kiranoot** [comment]
In general I'd much rather just remove it as a feature entirely. Offering any sort of reasonable guarantees on response time is really hard long term, and I'm now realizing that it shouldn't have been there at all. It seems to have been left from when I was testing it in beta by mistake.

The crux of the problem is that results have to be filtered by visibility on users. Loading thousands of user records takes a long time, lots of memory, etc. The way it's currently expressed in the database isn't conducive to rapid filtering on the database side either.

Limiting this to a single direction(user->posts) solves a lot of the visibility check problems.

**Comment by Earlopain** [comment]
What about limiting the visible users at once via pagination? I don't know how that works internally but limiting the view to say 75 users per page should only fetch those, right?


What do you mean with the last sentence? Going from user to favorites is easier than the other way around?

Anyways, if you don't think it's worth the trouble to implement/maintain this feel free to close the issue.

**Comment by kiranoot** [comment]
Going from a user to their favorite posts is easier, and faster. You only have to check for visibility of favorites for one user, and there are optimized routines for loading posts, paginating them, etc. based on a post id list. Users don't have as much tooling surrounding them, because they are rarely bulk loaded.

**Comment by kiranoot** [comment]
I'll make you a deal. If you come up with a way to load the users without having to iterate over the whole set in code and check visibility, the feature is yours.

**Comment by liamwhite** [comment]
Elasticsearch?

**Comment by kiranoot** [comment]
ES doesn't store the visible list of users because that involves the same lookup at index time, as well as at time of visibility change. The visibility is checked before lookup. Also you can view your own private favorites.

**Comment by Earlopain** [comment]
Nice, I'll see what I can do. Still new to rails so I doubt I can actually do much but taking a look won't hurt.

**Comment by Earlopain** [comment]
Fixed with #250
