### ISSUE TITLE
Cannot alias tags with invalid names to valid ones through BUR

### ISSUE THREAD

**Issue by bitWolfy** [e621ng/e621ng#261]
Specifically, the BUR form does not allow antecedent names to be invalid tags. The following error message is displayed:
```
Error: Antecedent name ':|' cannot begin with a colon (':') (create alias :| -> neutral_face)
```
This prevents such tags from being replaced with valid ones.

**Comment by kiranoot** [comment]
I'll have to create a few of these manually, or run them through the mass update tool without an alias. The way the name checks current run operates independently of the other checks. The reason that source tags are validated is to try and prevent situations where invalid tags are created through aliases, since they are usually inaccessible anyways. The ASCII check is explicitly disabled for these since that doesn't interfere with any other systems. I don't want to remove the check for source names because it's a good indicator of mistakes being made.
