### ISSUE TITLE
Empty related-tags list results in `[]` appearing

### ISSUE THREAD

**Issue by tj0mmi** [e621ng/e621ng#276]
When a tag has no related tags in the related tags viewer during uploading it shows an empty list object instead of nothing. 
See image

![image](https://user-images.githubusercontent.com/50883546/120925595-85355580-c6d9-11eb-83e0-1ec9215d8db5.png)

**Comment by Earlopain** [comment]
Sample request: https://e621.net/related_tag/bulk.json?query=black_and_fur

Unfortunately I can't seem to reproduce this on my install. I tried a few combinations of adding and removing tags after uploading a post but no luck. My json response for the tag is always the empty array which seems to get handled correctly.

If I had to guess I would say that the problem lies somewhere here, maybe at `with_unflattened_tags`. Can't look more into it without actually having the problem myself though.
https://github.com/zwagoth/e621ng/blob/1c61801bebefaf86d1065586393b8a793cb60e2e/app/logical/related_tag_calculator.rb#L57-L69

**Comment by tj0mmi** [comment]
> Sample request: https://e621.net/related_tag/bulk.json?query=black_and_fur
>
> My json response for the tag is always the empty array which seems to get handled correctly.

Huh weird, my json response is the following:
`{"black_and_fur":[["[]",0,0]]}`

As you can see, for me it returns an empty array as a string, which is identified as a tag and displayed to the user.

**Comment by Earlopain** [comment]
I  might have worded it a bit weird, I meant on my local install I get the empty array. The response you wrote is the same for me on the actual side. I just couldn't reproduce that response when testing on my local install.

**Comment by tj0mmi** [comment]
Something fixed this issue. The sample request you used now correctly returns an empty array instead of a string: `{"black_and_fur":[]}`

Tried looking for what change could possibly have fixed it, but couldn't find anything obvious. (Maybe something in `app/logical/related_tag_query.rb`?)
Hey, at least it works now ¯\\\_(ツ)_/¯
