### ISSUE TITLE
IQDB_Queries breaks if uploading local file with Cyrillic characters

### ISSUE THREAD

**Issue by bitWolfy** [e621ng/e621ng#300]
The issue can be replicated following these steps:
1. Download the file at the following URL: `https://d.furaffinity.net/art/rorarom/1627251837/1627251837.rorarom_анрпар1.jpg`
2. Add it via a "Choose file" dialogue on https://e621.net/iqdb_queries
3. Click "Search"

Instead of the results, or even the normal "Unexpected error occurred" error page, these steps result in a "Failbooru" error page, with the words "Something Broke" on it.

Video demo, courtesy of GokuRoku132:

https://user-images.githubusercontent.com/1503448/127193257-3e3ce309-be7e-4055-99cb-8c36b453acaa.mp4

**Comment by Earlopain** [comment]
The exception logger seems to be having trouble with the cyrillic characters. Throwing an exception in the exception handler doesn't sound too good and can probably result in displaying the bland error page.

The exception that gets displayed when doing it the other way (not exactly sure what they did there) I can't reproduce since iqdbs/iqdb isn't installed by default in the virtual machine and I can't be bothered to figure out how to get it up and running.

![image](https://user-images.githubusercontent.com/14981592/127206778-3e3c26db-fc5e-489b-83e3-f066b36fe968.png)

**Comment by Earlopain** [comment]
It's not actually the cyrillic characters like I originally wrote but rather the filename in `@headers` which contains utf8 code units (I think that's what they're called).

```ruby
{"authenticity_token"=>"[FILTERED]",
 "url"=>"",
 "file"=>
  #<ActionDispatch::Http::UploadedFile:0x0000558ff513be58
   @content_type="image/jpeg",
   @headers="Content-Disposition: form-data; name=\"file\"; filename=\"1627251837.rorarom_\xD0\xB0\xD0\xBD\xD1\x80\xD0\xBF\xD0\xB0\xD1\x801.jpg\"\r\n" + "Content-Type: image/jpeg\r\n",
   @original_filename="1627251837.rorarom_анрпар1.jpg",
   @tempfile=#<File:/tmp/RackMultipart20210927-10626-th7h0q.jpg>>,
 "commit"=>"Search"}
```
The issue here is fixable simply by passing the tempfile of the uploaded file to `IqdbProxy` like so: `IqdbProxy.query_file(params[:file].tempfile)`. This works because the headers are not passed to `Httparty` anymore which presumably tries to do some decoding/encoding with it otherwise. That doesn't change that the exception log doesn't handle the above params well. I played around a bit but couldn't get it to work.

@zwagoth Do you think I could simply pass in the tempfile? It works but seems more like a workaround to me. There's probably a better solution I don't know about.
