### ISSUE TITLE
Embed Ruffle to make SWF files work

### ISSUE THREAD

**Issue by maxwell-kalin** [e621ng/e621ng#573]
Just an idea 
https://ruffle.rs

greets

**Comment by DonovanDMC** [comment]
I'd rather we just leave flash in the past on the web, download a standalone flash player if you want to play them 🤷

**Comment by ata-star** [comment]
I see what you mean but its kinda a part of e621 in my opinion, ruffle is a modern replacement that is easy to implement. Flash is no more but the files are still there. What reason to keep them on e6 even, if you have to download them anyway.

at least make them play again when the Ruffle plugin is installed in the browser.

**Comment by DonovanDMC** [comment]
Iirc Earlopain said allowing ruffle would require lowering the content security policy (allowing unsafe-eval), which is no good

**Comment by DearFox** [comment]
What exactly is the problem that the ruffle extension cannot run the swf file directly on the site?

**Comment by DonovanDMC** [comment]
As far as I'm aware it isn't a "can't", it's a "_won't_" for reasons ranging from security issues to general lack of development time

**Comment by Deer-Spangle** [comment]
Is ruffle actually reliable enough to be worth it? I feel like most the time I've tried it on FA, it hasn't managed to run the swf file anyway?

**Comment by DearFox** [comment]
> Is ruffle actually reliable enough to be worth it? I feel like most the time I've tried it on FA, it hasn't managed to run the swf file anyway?

Well, I think it would be useful to allow the extension to run swf (if ruffle is installed in the user's browser, then it will work).
 But yes, ruffle should play AS1 and AS2 well, but still has some problems with AS3.
 I don't think adding ruffle itself to the e621.  Just let the user decide whether he wants to use this extension or not.
 
Regarding trust, it is difficult to say, since I have not checked its source code.  But it's open and has quite a bit of community attention, as far as I know.  So I trust it about as much as I trust any other open source software.
